name: validation
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
           echo "Testing addition (2 + 2)" 
           result=$(python -c "from calculator import add; print (float(add(2, 2)))") 
           if [ "$(printf "%.1f" $result)" != "4.0" ]; then
           echo "Addition test failed: Expected 4.0, Got $result" 
           exit 1
           fi
           
           echo "Testing subtraction (5 - 3)"
           result=$(python -c "from calculator import subtract; print(float (subtract(5, 3)))")
           if [ "$(printf "%.1f" $result)" != "2.0" ]; then
           echo "Subtraction test failed: Expected 2.0, Got $result"
           exit 1
           fi

           echo "Testing multiplication (3 * 3)"
           result=$(python -c "from calculator import multiply; print(float(multiply(3, 3)))")
           if [ "$(printf "%.1f" $result)" != "9.0" ]; then
           echo "Multiplication test failed: Expected 9.0, Got $result"
           exit 1
           fi

           echo "Testing division (10 / 2)"
           result=$(python -c "from calculator import divide; print(float(divide(10, 2)))")
           if [ "$(printf "%.1f" $result)" != "5.0" ]; then
           echo "Division test failed: Expected 5.0, Got $result"
           exit 1
           fi

           echo "Testing division zero (10 / 0)"
           result=$(python -c "from calculator import divide; print (divide(10, 0))")
           if [ "$result" != "Error! Division by zero." ]; then
           echo "Division by zero test failed: Expected 'Error! Division by zero.', Got $result"
           exit 1
           fi
           
           echo "All tests passed!"
