name: validation
on:
  workflow_dispatch:

jobs:
  test_calculator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run tests
        run: |
          echo "2\n2\n1" | python calculator.py | grep "The sum of 2 and 2 is 4.0"
          echo "5\n2\n2" | python calculator.py | grep "The difference of 5 and 2 is 3.0"
          echo "3\n3\n3" | python calculator.py | grep "The product of 3 and 3 is 9.0"
          echo "10\n2\n4" | python calculator.py | grep "The quotient of 10 and 2 is 5.0"
